### ISSUE TITLE
Ranges support

### ISSUE THREAD

**Issue by t3hk0d3** [bluemonk/ipaddress#26]
Please provide way to use ip addresses with ranges.

```ruby
ip1 = IPAddress('192.168.10.10')
ip2 = IPAddress('192.168.30.40')

ip = IPAddress('192.168.15.20')

(ip1..ip2).include? ip
```

**Comment by bjmllr** [comment]
It looks like `IPAddress::IPv4` just needs `succ` defined (`self + 1` will work), but for this use case `Range#cover?` would be a lot faster and already works on 0.8.0.

```
ip1 = IPAddress('192.168.10.10')
ip2 = IPAddress('192.168.30.40')

ip = IPAddress('192.168.15.20')
outside = IPAddress('192.168.31.20')

(ip1..ip2).cover?(ip) # => true
(ip1..ip2).cover?(outside) # => false
```

**Comment by t3hk0d3** [comment]
@bjmllr see PR#27. Adding ``#succ`` is worst way possible, since IP-addresses are actually 32-bit/128-bit integers, and Ruby can work in appropriate way with range of integers, you just need to add ``#to_int`` methods.
