### ISSUE TITLE
.first and .last method of an IPv4 /32 address is not working properly

### ISSUE THREAD

**Issue by nwit-kgn** [bluemonk/ipaddress#36]
In version 0.8.0

I get following result using .first and .last on an IPv4 /32 address:
[66] pry(main)> ip = IPAddress('192.168.1.2/32')
=> #<IPAddress::IPv4:0xc001e58
 @address="192.168.1.2",
 @octets=[192, 168, 1, 2],
 @prefix=32,
 @u32=3232235778>
[67] pry(main)> ip.first
=> #<IPAddress::IPv4:0xc02fed4
 @address="192.168.1.3",
 @octets=[192, 168, 1, 3],
 @prefix=32,
 @u32=3232235779>
[68] pry(main)> ip.last
=> #<IPAddress::IPv4:0xc052498
 @address="192.168.1.1",
 @octets=[192, 168, 1, 1],
 @prefix=32,
 @u32=3232235777>

**Comment by mikemackintosh** [comment]
This has been included here - https://github.com/bluemonk/ipaddress/pull/61
