### ISSUE TITLE
using split() fails if you request more than 32 networks

### ISSUE THREAD

**Issue by neoice** [bluemonk/ipaddress#40]
a Class B network, like "10.13.0.0/16" contains 256 Class C networks [1]. consider the example code:

    require 'ipaddress'
    x = IPAddress('10.13.0.0/16')
    c_class_count = (x.hosts.length / 256) + 1
    x.split(c_class_count)

this results in the following error:

    ArgumentError: New prefix must be between 16 and 32
    from PATH/vendor/cache/ruby/1.9.1/gems/ipaddress-0.8.0/lib/ipaddress/ipv4.rb:684:in `subnet'

I also used "10.0.0.0/8" and reproduced the same behavior.

[1] http://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#IPv4_CIDR_blocks

**Comment by mikemackintosh** [comment]
This has been included here - https://github.com/bluemonk/ipaddress/pull/61
