### ISSUE TITLE
Move ownership to community

### ISSUE THREAD

**Issue by t3hk0d3** [bluemonk/ipaddress#63]
There is lots of issues, PRs and etc. There is initiative people.

But everything ends on repository owner absence. He even ignores emails.

Considering this gem is quite popular and used in many projects i think community should take care of it.

Here is dispute on ruby gems to move gem ownership to community:

http://help.rubygems.org/discussions/suggestions/7851-reporting-abuse-on-ipaddress-author-missing

**Comment by DiogoAndre** [comment]
I don't think the author is missing. He has responded to issues in the recent past, maybe he's just not as active as you wished. 

If you're not happy with the way this project is being handled you can just fork it and make it your own.

That abuse report was totally unnecessary.

**Comment by t3hk0d3** [comment]
@DiogoAndre 
there is lots of PR and issues still ignored. Some PRs hanging for years.

> He has responded to issues in the recent past, maybe he's just not as active as you wished.

@bluemonk github activity is empty for few months.

> If you're not happy with the way this project is being handled you can just fork it and make it your own.
> That abuse report was totally unnecessary.

I think gem should be actively maintained, because i use it in my projects.

I am not happy with issues being ignored and PRs contributors time being wasted.

**Comment by jmehnle** [comment]
@t3hk0d3, this issue report is not constructive, just complaining. Please stop it. Just fork the gem and be done with it.

**Comment by t3hk0d3** [comment]
@jmehnle Its constructive. 
I think @bluemonk just should move repository into organization, and let initiative people like @mikemackintosh accept PRs.

Otherwise this is just another **dead** unmaintained gem.
There is should be single upstream to collect all positive changes, not shitload of forks.

**Comment by bluemonk** [comment]
Mike already has full access to the github repo. He has been accepting PRs
since a while now, or am I missing something?

**Comment by t3hk0d3** [comment]
@bluemonk well, it fine than.

**Comment by mikemackintosh** [comment]
I think the general concern is around the actual built gem. We have the ability to manage the repo, but the gem itself is unmanaged on rubygems.

**Comment by t3hk0d3** [comment]
@mikemackintosh that was reason why i've created abuse on rubygems.

**Comment by DiogoAndre** [comment]
I see.. makes sense. It isn't complicated to add another owner to the Gem on Rubygems. [gem owner command](http://guides.rubygems.org/command-reference/#gem-owner)

Maybe @bluemonk can add @mikemackintosh, and we'll all be happy. :smile:

**Comment by bf4** [comment]
FYI, y'all https://github.com/rubygems/rubygems.org/issues/725 and https://github.com/rails-girls-summer-of-code/projects/issues/31
