### ISSUE TITLE
Avoid Ruby 1.8 compatibility when using Ruby 2.1.8

### ISSUE THREAD

**Issue by wpiekutowski** [bluemonk/ipaddress#67]
There's a small problem in https://github.com/bluemonk/ipaddress/blob/master/lib/ipaddress.rb#L217.
This regular expression is matching not only Ruby 1.8, but also 2.1.8. Because of that, when you upgrade to any Ruby with a version similar to x.1.8, you'll get a ton of warnings similar to:
```
.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/mime.rb:25: warning: Hash#index is deprecated; use Hash#key
```

That code is correctly using Hash#key, but due to the `alias` made in

https://github.com/bluemonk/ipaddress/blob/master/lib/ipaddress.rb#L219

Hash#key becomes an alias to Hash#index and actually Hash#index is called, which results in a lot of depreciation warnings.

**Comment by wpiekutowski** [comment]
Would it be possible to release 0.8.3 with only this small fix? If so, I'm happy to create a proper branch based on 0.8.2.

**Comment by bluemonk** [comment]
What a silly bug! Good catch, thanks for the PR.
I will release 0.8.3 now.

**Comment by wpiekutowski** [comment]
Awesome, thank you for a quick reaction.
